'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

const previewStops=[{type:'IC',name:'相模原愛川',distance:'9.4',eta:'10:48'},{type:'PA',name:'厚木',distance:'5.3',eta:'10:44'},{type:'IC',name:'圏央厚木',distance:'4.2',eta:'10:43'}];
export default function PinLogin({configured}:{configured:boolean}){
 const [pin,setPin]=useState(''),[error,setError]=useState(configured?'':'現在PINコードが設定されていません。管理者が設定画面からPINコードを設定してください。'),[busy,setBusy]=useState(false); const router=useRouter();
 async function submit(event:FormEvent){event.preventDefault();if(!/^\d{4}$/.test(pin)){setError('PINコードは4桁の数字で入力してください。');return}setBusy(true);const response=await fetch('/api/pin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});const result=await response.json() as {error?:string};setBusy(false);if(response.ok){router.replace('/nav');router.refresh()}else{setPin('');setError(result.error??'認証できませんでした。')}}
 return <main className="app-shell"><section className="nav-preview" aria-hidden="true"><header className="route-header"><span>C4</span><strong>圏央道</strong><b>上り・久喜方面</b></header><div className="stop-stack">{previewStops.map(stop=><article className="stop-card" key={stop.name}><div className="stop-title"><span>{stop.type}</span><strong>{stop.name}</strong></div><div className="stop-metrics"><b>{stop.distance}<small>km</small></b><b>{stop.eta}<small>通過</small></b></div></article>)}</div><div className="current-marker"><i/>現在地</div></section><section className="pin-panel"><div className="pin-brand"><span>C4</span><div><b>高速道路アシスト</b><small>HIGHWAY ASSIST</small></div></div><p className="eyebrow">ACCESS PIN</p><h1>4桁のPINを入力</h1><p className="intro">許可された利用者のみナビ画面を使用できます。</p><form className="pin-form" onSubmit={submit}><label htmlFor="pin">PINコード</label><input id="pin" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="••••" autoComplete="one-time-code" disabled={!configured||busy}/>{error&&<p className="form-error" role="alert">{error}</p>}<button type="submit" disabled={!configured||busy}>{busy?'確認中…':'ナビを開く'}</button></form><a className="settings-link" href="/settings">管理者設定</a><p className="security-note">認証情報はサーバー側で安全に確認されます</p></section></main>;
}
