'use client';
/* eslint-disable @next/next/no-html-link-for-pages */
import { FormEvent, useState } from 'react';

export default function SettingsPanel({email,initialConfigured}:{email:string;initialConfigured:boolean}){
 const[configured,setConfigured]=useState(initialConfigured),[pin,setPinValue]=useState(''),[confirmation,setConfirmation]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const clean=(value:string)=>value.replace(/\D/g,'').slice(0,4);
 async function save(event:FormEvent){event.preventDefault();setError('');setMessage('');if(!/^\d{4}$/.test(pin)){setError('PINコードは4桁の数字で入力してください。');return}if(pin!==confirmation){setError('確認用PINコードが一致しません。');return}setBusy(true);const response=await fetch('/api/settings/pin',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin,confirmation})});const result=await response.json() as {error?:string};setBusy(false);if(response.ok){setConfigured(true);setPinValue('');setConfirmation('');setMessage('新しいPINコードを設定しました。以前の利用者セッションは無効になりました。')}else setError(result.error??'保存できませんでした。')}
 async function clear(){if(!confirm('現在設定されているPINコードをクリアします。よろしいですか？'))return;setBusy(true);const response=await fetch('/api/settings/pin',{method:'DELETE'});setBusy(false);if(response.ok){setConfigured(false);setMessage('PINコードをクリアしました。新しいPINを設定するまでナビにはログインできません。');setError('')}else setError('PINコードをクリアできませんでした。')}
 return <main className="settings-shell"><section className="settings-wide"><header className="settings-header"><div className="pin-brand"><span>⚙</span><div><b>高速道路アシスト</b><small>管理設定</small></div></div><a href="/api/admin/logout">Googleログアウト</a></header><div className="admin-grid"><aside><p className="eyebrow">ADMIN ACCOUNT</p><h1>アクセス設定</h1><div className="status-block"><small>ログイン中</small><strong>{email}</strong></div><div className="status-block"><small>PIN設定状態</small><strong className={configured?'ok':'warn'}>{configured?'● PIN設定済み':'● PIN未設定'}</strong></div><a className="back-link" href="/">ナビへ戻る</a></aside><section className="settings-form"><h2>{configured?'PINコードを変更':'PINコードを設定'}</h2><p>4桁の数字を設定してください。現在のPINは表示されません。</p><form onSubmit={save}><label>新しいPINコード<input value={pin} onChange={e=>setPinValue(clean(e.target.value))} inputMode="numeric" maxLength={4} placeholder="••••"/></label><label>新しいPINコード（確認）<input value={confirmation} onChange={e=>setConfirmation(clean(e.target.value))} inputMode="numeric" maxLength={4} placeholder="••••"/></label>{error&&<p className="form-error">{error}</p>}{message&&<p className="form-success">{message}</p>}<button className="primary-button" disabled={busy}>{busy?'処理中…':configured?'PINコードを変更':'PINコードを設定'}</button></form>{configured&&<div className="danger-zone"><h3>PINコードをクリア</h3><p>クリア後は、新しいPINを設定するまで通常利用者はログインできません。</p><button onClick={clear} disabled={busy}>PINコードをクリア</button></div>}</section></div></section></main>;
}
